version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    networks:
      - overlay
    command: python bot.py
    restart: always
    env_file:
      - ".env"
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - overlay
    volumes:
      - ./redisdata:/var/lib/redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:14.4
    container_name: postgresql
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    networks:
      - overlay
    ports:
      - 5431:5432
    volumes:
    - ./pgdata:/var/lib/postgresql/data

networks:
  overlay:
